"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.shrug = exports.shocked = exports.sad = exports.kiss = exports.hug = exports.headpat = exports.happy = exports.fight = exports.dance = exports.top = exports.lyrics = exports.genius = exports.hamster = exports.capybara = exports.bunny = exports.sloth = exports.redPanda = exports.panda = exports.koala = exports.turtle = exports.cat = exports.puppy = exports.kitten = exports.dog = void 0;
// ANIMALS
var dog_1 = require("./animals/dog");
Object.defineProperty(exports, "dog", { enumerable: true, get: function () { return dog_1.endpoint; } });
var kitten_1 = require("./animals/kitten");
Object.defineProperty(exports, "kitten", { enumerable: true, get: function () { return kitten_1.endpoint; } });
var puppy_1 = require("./animals/puppy");
Object.defineProperty(exports, "puppy", { enumerable: true, get: function () { return puppy_1.endpoint; } });
var cat_1 = require("./animals/cat");
Object.defineProperty(exports, "cat", { enumerable: true, get: function () { return cat_1.endpoint; } });
var turtle_1 = require("./animals/turtle");
Object.defineProperty(exports, "turtle", { enumerable: true, get: function () { return turtle_1.endpoint; } });
var koala_1 = require("./animals/koala");
Object.defineProperty(exports, "koala", { enumerable: true, get: function () { return koala_1.endpoint; } });
var panda_1 = require("./animals/panda");
Object.defineProperty(exports, "panda", { enumerable: true, get: function () { return panda_1.endpoint; } });
var red_panda_1 = require("./animals/red-panda");
Object.defineProperty(exports, "redPanda", { enumerable: true, get: function () { return red_panda_1.endpoint; } });
var sloth_1 = require("./animals/sloth");
Object.defineProperty(exports, "sloth", { enumerable: true, get: function () { return sloth_1.endpoint; } });
var bunny_1 = require("./animals/bunny");
Object.defineProperty(exports, "bunny", { enumerable: true, get: function () { return bunny_1.endpoint; } });
var capybara_1 = require("./animals/capybara");
Object.defineProperty(exports, "capybara", { enumerable: true, get: function () { return capybara_1.endpoint; } });
var hamster_1 = require("./animals/hamster");
Object.defineProperty(exports, "hamster", { enumerable: true, get: function () { return hamster_1.endpoint; } });
// MUSIC
var genius_1 = require("./music/genius");
Object.defineProperty(exports, "genius", { enumerable: true, get: function () { return genius_1.endpoint; } });
var lyrics_1 = require("./music/lyrics");
Object.defineProperty(exports, "lyrics", { enumerable: true, get: function () { return lyrics_1.endpoint; } });
var top_1 = require("./music/top");
Object.defineProperty(exports, "top", { enumerable: true, get: function () { return top_1.endpoint; } });
// ANIME
var dance_1 = require("./anime/dance");
Object.defineProperty(exports, "dance", { enumerable: true, get: function () { return dance_1.endpoint; } });
var fight_1 = require("./anime/fight");
Object.defineProperty(exports, "fight", { enumerable: true, get: function () { return fight_1.endpoint; } });
var happy_1 = require("./anime/happy");
Object.defineProperty(exports, "happy", { enumerable: true, get: function () { return happy_1.endpoint; } });
var headpat_1 = require("./anime/headpat");
Object.defineProperty(exports, "headpat", { enumerable: true, get: function () { return headpat_1.endpoint; } });
var hug_1 = require("./anime/hug");
Object.defineProperty(exports, "hug", { enumerable: true, get: function () { return hug_1.endpoint; } });
var kiss_1 = require("./anime/kiss");
Object.defineProperty(exports, "kiss", { enumerable: true, get: function () { return kiss_1.endpoint; } });
var sad_1 = require("./anime/sad");
Object.defineProperty(exports, "sad", { enumerable: true, get: function () { return sad_1.endpoint; } });
var shocked_1 = require("./anime/shocked");
Object.defineProperty(exports, "shocked", { enumerable: true, get: function () { return shocked_1.endpoint; } });
var shrug_1 = require("./anime/shrug");
Object.defineProperty(exports, "shrug", { enumerable: true, get: function () { return shrug_1.endpoint; } });
